name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  cool_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: List files and simple echo command
        #uses: actions/checkout@v2
        run: |
           echo "Hello World!"
           ls
           pwd
