name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  cool_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Echo command
        run: echo "Hello World!"
           
      - name: list files 
        run: ls
        
      - name: see path 
        run: pwd
